/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FindTheOut */

#ifndef _Included_FindTheOut
#define _Included_FindTheOut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FindTheOut
 * Method:    receive
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_FindTheOut_receive
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
